name: "Release"

on:
  push:
    branches:
      - development
      - next
  workflow_dispatch:

permissions:
    contents: write
    issues: write
    deployments: write
    id-token: write # to enable use of OIDC for npm provenance and trusted publishing

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  lint-test:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  build-packages:
    needs: 'setup'
    uses: ./.github/workflows/reusable_build.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  release:
    needs: ['setup','lint-test','build-packages']
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
        run: npx semantic-release